"""Application settings."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

BASE_DIR = Path(__file__).resolve().parent.parent
BACKEND_DIR = Path(__file__).resolve().parent
DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{BACKEND_DIR / 'csr.db'}")

SECRET_KEY = os.getenv("SECRET_KEY", "change-me-in-production-9f8d7c6b5a4e3d2c")
COOKIE_NAME = "csr_session"
COOKIE_MAX_AGE = 60 * 60 * 24  # 24 hours

UPLOAD_DIR = BASE_DIR / "uploads"
UPLOAD_DIR.mkdir(exist_ok=True)

OUTPUT_DIR = BASE_DIR / "csr-generation-module" / "output"

SECTION_MAP = {
    1: "Title Page",
    2: "Synopsis",
    3: "Table of Contents",
    4: "List of Abbreviations",
    5: "Ethics",
    6: "Investigators and Study Administrative Structure",
    7: "Introduction",
    8: "Study Objectives",
    9: "Investigational Plan",
    10: "Study Patients",
    11: "Efficacy Evaluation",
    12: "Safety Evaluation",
    13: "Discussion and Overall Conclusions",
    14: "Tables, Figures and Graphs",
    15: "Reference List",
    16: "Appendices",
}

# Sections generated by the orchestrator (3 & 4 are auto-generated)
# Currently generating Section 1 (Title Page) only
GENERATED_SECTIONS = [1]
